[build]
builder = "RAILPACK"
buildCommand = "pnpm -F main build && cp -r apps/main/.next/static apps/main/.next/standalone/apps/main/.next/static"
watchPatterns = ["/apps/main/**"]

[deploy]
preDeployCommand = "pnpm -F main db:migrate"
startCommand = "pnpm -F main start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
